### ISSUE TITLE
Export either Vault.Lazy or Vault.Strict as Vault, again

### ISSUE THREAD

**Issue by amigalemming** [HeinrichApfelmus/vault#22]
In vault-0.2 we had the module `Data.Vault` which was split into `Data.Vault.Lazy` and `Data.Vault.Strict` in vault-0.3. Can I have back a `Data.Vault` that re-exports either `Data.Vault.Lazy` and `Data.Vault.Strict`? This would be analogous to `Data.Map` that re-exports `Data.Map.Lazy`. It would both show the programmer the prefered `Vault` variant and allows him to support both vault-0.2 and vault-0.3 by importing `Data.Vault`.
However in order to allow simple version ranges like `vault >=0.2 && <0.4` it would be necessary to deprecate vault-0.3 at Hackage.

**Comment by HeinrichApfelmus** [comment]
Well, unlike `Data.Map`, I don't wish to claim that I know what the preferred version is. At one point, I even used both versions simultaneously in my reactive-banana package. (The lazy variant was used to implement a lazy lookup table in the context of recursion, the strict variant was used to implement a lookup table whose values had to be stored in WHNF.)

Why exactly do you need the preferred version? I guess you don't want to switch to vault-0.3 because of dependencies?

**Comment by amigalemming** [comment]
On Tue, 8 Dec 2015, Heinrich Apfelmus wrote:

> Why exactly do you need the preferred version? I guess you don't want to 
> switch to vault-0.3 because of dependencies?

I want to upgrade step by step. There is the reactive-banana branch and 
the synthesizer-llvm branch of packages that depend on vault. I want to 
allow vault-0.3 on one branch without becoming incompatible with the other 
branch still using vault-0.2.

**Comment by sjakobi** [comment]
I guess this issue isn't relevant anymore and can be closed. Please reopen if you disagree.
